### ISSUE TITLE
Position Sticky Not Working

### ISSUE THREAD

**Issue by LayZNimrod** [imd1005-web-development-winter-2023/assignment-02-LayZNimrod#2]
position sticky in my css code not working

**Comment by neilmispelaar** [comment]
Thanks for creating an issue @LayZNimrod  - will have a look at this today!

**Comment by LayZNimrod** [comment]
@neilmispelaar should I just give up on position sticky and bring the header back to its original state or just wait a bit longer for an answer.

**Comment by neilmispelaar** [comment]
@LayZNimrod sorry it’s been a crazy day. Will have a look at it later tonight when things calm down.

**Comment by LayZNimrod** [comment]
@neilmispelaar ok sorry for bothering you sir. I hope that things calm down soon.

**Comment by LayZNimrod** [comment]
@neilmispelaar I am very close to getting it to work but I am wondering if I should abandon it and just submit it as it is without the scroll. I also wanted you to know that my website is actually a lot more suited for mobile devices instead of pc screens.

**Comment by neilmispelaar** [comment]
@LayZNimrod 

Congratulations! I just tested your latest code and it's working for me on Safari (see video below):

https://user-images.githubusercontent.com/9325038/219885175-5767b15b-7385-478e-8da0-ee6d0e4e8a73.mp4

Let me know if you still need help with this, otherwise I'll close the issue. 

Thanks for your patience.
